In [45]:
import pandas as pd

In [46]:
import os

In [47]:
os.chdir("//Users/huongvu/Documents/Fall 2021/Bass Connection/Ideal Point Estimates")

In [48]:
os.getcwd()

'/Users/huongvu/Documents/Fall 2021/Bass Connection/Ideal Point Estimates'

In [51]:
df1 = pd.read_csv("Vaccine_Producer.csv")

In [52]:
df2 = pd.read_csv("idealpointsestimates_final.csv")

In [53]:
df_merge = pd.merge(df1, df2, on=["Countryname"])

In [54]:
df_merge

,Developer,Countryname,IdealPointAll
0,Pfizer/BioNTech,Argentina,-0.081344
1,Laboratorios Richmond S.A.C.I.F.,Argentina,-0.081344
2,Beijing Institute of Biological Products - Rep...,Argentina,-0.081344
3,CanSino Biologics,Argentina,-0.081344
4,CanSino Biologics,Argentina,-0.081344
...,...,...,...
121,Gamaleya,United Arab Emirates,-0.664320
122,Gamaleya,Uzbekistan,-0.354059
123,Gamaleya,Venezuela,-1.647183
124,Gamaleya,Vietnam,-0.925060
125,Sinovac,Zimbabwe,-1.174122

In [57]:
df3 = pd.read_csv("Country_code.csv")

In [62]:
country_code_drop = df3.drop_duplicates()

In [63]:
country_code_drop.to_csv('Country_code.csv')

In [66]:
df_merge_1 = pd.merge(df2, country_code_drop, on=["Countryname"])

In [67]:
df_merge_1

     Countryname  IdealPointAll iso3c
0    Afghanistan      -0.753452   AFG
1        Albania       1.094502   ALB
2        Algeria      -1.112967   DZA
3        Andorra       0.814269   AND
4         Angola      -0.647945   AGO
..           ...            ...   ...
186      Vietnam      -0.925060   VNM
187        Yemen      -0.717542   YEM
188   Yugoslavia       0.474767   YUG
189       Zambia      -0.636046   ZMB
190     Zimbabwe      -1.174122   ZWE

[191 rows x 3 columns]

In [68]:
df_merge_1 .to_csv('idealpointsestimates_iso.csv')

In [79]:
df4 = pd.read_csv("idealpointsestimates_iso.csv")

In [80]:
df5 = pd.read_csv("Pricing_data.csv")

In [81]:
df_merge_2 = pd.merge(df4, df5, on=["Countrycode"])

In [82]:
df_merge_2

,Unnamed: 0,Countryname,IdealPointAll,Countrycode,Date,Developer,Price Per Dose,Price - Average,Z-Score
0,0,Afghanistan,-0.753452,AFG,9/29/20 0:00,AstraZeneca,3.00,-0.15,-0.14
1,0,Afghanistan,-0.753452,AFG,9/29/20 0:00,Novavax,3.00,-0.34,-0.15
2,0,Afghanistan,-0.753452,AFG,6/4/20 0:00,AstraZeneca,2.50,-0.65,-0.63
3,1,Albania,1.094502,ALB,3/25/21 0:00,Gamaleya,9.75,0.61,0.16
4,2,Algeria,-1.112967,DZA,3/29/21 0:00,Janssen,10.00,0.73,0.97
...,...,...,...,...,...,...,...,...,...
1257,190,Zimbabwe,-1.174122,ZWE,6/4/20 0:00,AstraZeneca,2.50,-0.65,-0.63
1258,190,Zimbabwe,-1.174122,ZWE,3/15/21 0:00,Sinovac,10.00,-5.33,-0.80
1259,190,Zimbabwe,-1.174122,ZWE,4/6/21 0:00,Sinovac,10.00,-5.33,-0.80
1260,190,Zimbabwe,-1.174122,ZWE,1/20/21 0:00,Pfizer/BioNTech,6.75,-6.64,-0.94
1261,190,Zimbabwe,-1.174122,ZWE,3/29/21 0:00,Pfizer/BioNTech,6.75,-6.64,-0.94

In [83]:
df_merge_2.to_csv('pricingdata_idealpoint.csv')

In [84]:
df6 = pd.read_csv("pricingdata_idealpoint.csv")

In [85]:
df7 = pd.read_csv("producer_idealpoint.csv")

In [86]:
df_merge_3 = pd.merge(df6, df7, on=["Developer"])

In [87]:
df_merge_3

,Unnamed: 0_x,Unnamed: 0.1,Countryname_x,IdealPointAll,Countrycode,Date,Developer,Price Per Dose,Price - Average,Z-Score,Unnamed: 0_y,Countryname_y,IdealPointAll/Producer
0,0,0,Afghanistan,-0.753452,AFG,9/29/20 0:00,AstraZeneca,3.0,-0.15,-0.14,7,Argentina,-0.081344
1,0,0,Afghanistan,-0.753452,AFG,9/29/20 0:00,AstraZeneca,3.0,-0.15,-0.14,8,Argentina,-0.081344
2,0,0,Afghanistan,-0.753452,AFG,9/29/20 0:00,AstraZeneca,3.0,-0.15,-0.14,13,Argentina,-0.081344
3,0,0,Afghanistan,-0.753452,AFG,9/29/20 0:00,AstraZeneca,3.0,-0.15,-0.14,16,Argentina,-0.081344
4,0,0,Afghanistan,-0.753452,AFG,9/29/20 0:00,AstraZeneca,3.0,-0.15,-0.14,17,United States,2.701566
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19461,1259,190,Zimbabwe,-1.174122,ZWE,4/6/21 0:00,Sinovac,10.0,-5.33,-0.80,113,Thailand,-0.447101
19462,1259,190,Zimbabwe,-1.174122,ZWE,4/6/21 0:00,Sinovac,10.0,-5.33,-0.80,114,Thailand,-0.447101
19463,1259,190,Zimbabwe,-1.174122,ZWE,4/6/21 0:00,Sinovac,10.0,-5.33,-0.80,119,Ukraine,1.160707
19464,1259,190,Zimbabwe,-1.174122,ZWE,4/6/21 0:00,Sinovac,10.0,-5.33,-0.80,120,Ukraine,1.160707
19465,1259,190,Zimbabwe,-1.174122,ZWE,4/6/21 0:00,Sinovac,10.0,-5.33,-0.80,125,Zimbabwe,-1.174122

In [88]:
df_merge_3.to_csv('pricingdata_producer_idealpoint.csv')

In [98]:
df8 = pd.read_csv("Vaccine_developer.csv")

In [99]:
df9 = df8.drop_duplicates()

In [100]:
df9

      Unnamed: 0        Developer
0              0      AstraZeneca
1              1          Novavax
2              2      AstraZeneca
3              3         Gamaleya
4              4          Janssen
...          ...              ...
1257        1257      AstraZeneca
1258        1258          Sinovac
1259        1259          Sinovac
1260        1260  Pfizer/BioNTech
1261        1261  Pfizer/BioNTech

[1262 rows x 2 columns]

In [96]:
df9.to_csv('Vaccine_developer_1.csv')